name: Android CI (manual)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Debug: list workspace and show gradlew header"
        run: |
          ls -la
          if [ -f ./gradlew ]; then
            echo "--- gradlew (first 40 lines) ---"
            sed -n '1,40p' ./gradlew
          else
            echo "gradlew not found"
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build
